##TAREA 3
_Jhojan Stiven Zea Fernandez_

_CC 1037669632_


##PUNTO 1

Encontrar el SVD (Singular value decomposition) de la matriz

$$A=\begin{pmatrix}
1 & 2 \\
0 & -1 \\
3 & -2
\end{pmatrix}
$$

_Solucion_

Encontramos $A^{*}$, ya que todos los elementos de la matriz estan en $\mathbb{R}$ entonces $A^{*}=A^{T}$

$$A^{*}=\begin{pmatrix}
1 & 0 & 3 \\
2 & -1 & -2
\end{pmatrix}$$

UUtilizando el codigo de abajo, encontramos $AA^{*}$

$$AA^{*}=\begin{pmatrix}
1 & 2 \\
0 & -1 \\
3 & -2
\end{pmatrix}
\begin{pmatrix}
1 & 0 & 3 \\
2 & -1 & -2
\end{pmatrix}
=\begin{pmatrix}
5 & -2 & -1 \\
-2 & 1 & 2 \\
-1 & 2 & 13
\end{pmatrix}$$

Usando el codigo de abajo, encontramos $A^{*}A$

$$A^{*}A=\begin{pmatrix}
1 & 0 & 3 \\
2 & -1 & -2
\end{pmatrix}
\begin{pmatrix}
1 & 2 \\
0 & -1 \\
3 & -2
\end{pmatrix}
=\begin{pmatrix}
10 & -4 \\
-4 & 9
\end{pmatrix}$$







In [10]:
import numpy as np

A = np.array([[1, 2], [0, -1], [3, -2]])
A_adj = A.transpose()
A_adj_A = np.dot(A_adj, A)
A_A_adj = np.dot(A, A_adj);
print("AA*")
print(A_A_adj)
print("A*A:")
print(A_adj_A)


AA*
[[ 5 -2 -1]
 [-2  1  2]
 [-1  2 13]]
A*A:
[[10 -4]
 [-4  9]]


Utilizando la definicion para el polinomio caracteristico de una matriz $p(\lambda)=|A-λI|=0$ calculamos el polinomio caracteristico de la matriz $AA^{*}$
con ayuda de Gemini para no extender el proceso.

$$p(\lambda)=|AA^{*}-λI|= |\begin{pmatrix}
5-\lambda & -2 & -1 \\
-2 & 1-\lambda &2 \\
-1 & 2 & 13-\lambda
\end{pmatrix}|=-\lambda^{3}+19\lambda^{2}-74\lambda=0$$

De manera obvia, se puede sacar el factor $\lambda$ de cada termino, por lo cual tenemos ya un autovalor $\lambda_{3}=0$, los otros dos se calculan utilizando la calculadora grafica desmos y se ordenan de mayor a menor.
$$\lambda^1_1=13.53$$
$$\lambda^1_2=5.47$$
$$\lambda^1_3=0$$

Siguiendo el mismo procedimiento para la matriz $A^{*}A$, podemos encontrar que su polimomio caracteristico es:
$$p(\lambda)=|A^{*}A-λI|=\lambda^{2}-19\lambda+74$$
y sus autovalores, ordenados de mayor a menor son:
$$\lambda^2_1=13.53$$
$$\lambda^2_2=5.47$$

Como se puede comprobar en el siguiente codigo

In [18]:
import numpy as np

A = np.array([[1, 2], [0, -1], [3, -2]])
A_adj = A.transpose()
A_adj_A = np.dot(A_adj, A)
A_A_adj = np.dot(A, A_adj);


Valores_propios, Vectores_propios = np.linalg.eig(A_A_adj)
Valores_propios2, Vectores_propios2 = np.linalg.eig(A_adj_A)
print("Valores propios de AA*")
print(Valores_propios)
print("Valores propios de A*A")
print(Valores_propios2)



Valores propios de AA*
[ 0.          5.46887113 13.53112887]
Valores propios de A*A
[13.53112887  5.46887113]


Los valores singulares se calculan como la raiz de los valores propios, por tanto
$$\sigma_1=\sqrt{13.53} ≈ 3.68$$
$$\sigma_2=\sqrt{5.47} ≈ 2.34$$

Se calculan los autovectores unitarios de $AA^{*}$, los cuales son las columnas de la matriz $U$, con el codigo de python que se puede ver mas abajo, ya que python no entrega los autovectores necesariamente ordenados, se utiliza wolfram alpha para hacer la comprobacion de que autovalores le corresponden a cada vector con el fin de ordenarlos de mayor a menor.

$$U_1=\begin{pmatrix}
-0.16 \\
0.18\\
0.97
\end{pmatrix}$$

$$U_2=\begin{pmatrix}
-0.92 \\
0.32 \\
0.21
\end{pmatrix}$$

$$U_3=\begin{pmatrix}
-0.35 \\
-0.93 \\
0.12
\end{pmatrix}$$

Con el mismo codigo, se calculan los autovalores de $A^{*}A$, los cuales son las columnas de la matriz $V$

$$V_1=\begin{pmatrix}
0.75 \\
-0.66
\end{pmatrix}$$

$$V_2=\begin{pmatrix}
0.66 \\
0.75
\end{pmatrix}$$


In [24]:
import numpy as np

A = np.array([[1, 2], [0, -1], [3, -2]])
A_adj = A.transpose()
A_adj_A = np.dot(A_adj, A)
A_A_adj = np.dot(A, A_adj);


Valores_propios, Vectores_propios = np.linalg.eig(A_A_adj)
Valores_propios2, Vectores_propios2 = np.linalg.eig(A_adj_A)
print("Vectores propios de AA*")
print(Vectores_propios)
print("Vectores propios de A*A")
print(Vectores_propios2)


Vectores propios de AA*
[[-0.34874292 -0.92414019 -0.15602335]
 [-0.92998111  0.32057232  0.17991254]
 [ 0.11624764 -0.20784199  0.97123025]]
Vectores propios de A*A
[[ 0.74967818  0.66180256]
 [-0.66180256  0.74967818]]


Con todo lo anterior se construyen $U,V^{T}$ y $Σ$

$$A=U \Sigma V^{T}=\begin{pmatrix}
0.16 &0.92&-0.35\\
-0.18 & -0.32 & -0.93\\
-0.97 & 0.21 & 0.12
\end{pmatrix}
\begin{pmatrix}
3.68 & 0 \\
0 & 2.34 \\
0 & 0
\end{pmatrix}
\begin{pmatrix}
-0.75 & 0.66\\
0.66 & 0.75
\end{pmatrix}$$


Debido a las ambiguedades en la descomposicion SVD, y sabiendo que un vector propio por un escalar tambien es un vector propio de la matriz, se utilizó wolfram alpha para descifrar la correcta descomposicion de la Matriz, multiplicando por -1 los vectores $U_1, U_2, V_1$

La descomposicion se puede comprobar con el siguiente codigo


In [33]:
import numpy as np

U = np.array([[0.16, 0.92, -0.35],
              [-0.18, -0.32, -0.93],
              [-0.97, 0.21, 0.12]])

E = np.array([[3.68, 0],
              [0, 2.34],
              [0, 0]])

UE = np.dot(U, E)

VT = np.array([[-0.75, 0.66],
              [0.66, 0.75]])

UEVT = np.dot(UE, VT)
print(UEVT)




[[ 9.792480e-01  2.003208e+00]
 [ 2.592000e-03 -9.987840e-01]
 [ 3.001524e+00 -1.987386e+00]]


Este calculo (debido a redondear los calculos a 2 decimales) es aproximadamente igual a la matriz $A$, por lo tanto se prueba que la descomposicion SVD de esta matriz fué realizada correctamente

#Punto 2

**Ambiguedad en el SVD**

Hay una gran cantidad de ambiguedad en la decomposicion SVD. Considere la matriz identidad. En cuantas formas validas se puede escribir $I_n=U\Sigma V^{T}$? Asuma que ya has decidido que vectores ortonormales columna $u_1, u_2, \cdots , u_r$, de la matriz $U_r$, que corresponden a algunos valores singulares diferentes de cero de la matriz $A\quad m\times n$. Correspondientemente, van a haber $v_1,v_2,\cdots,v_r$ vectores propopios ortonormales que son columnas de la matriz $V_r$. Se podrian cambiar los signos de esos vectores, resultando en $2^{r}$ posibilidades para escoger los autovectores ortonormales $v_i$ y solo una de esas combinaciones dá la factorizacion SVD correcta. Como se escoge la matriz $V_r$ Correcta?, por favor comentar sobre los autovectores que corresponden a autovalores de cero.

_Solucion_

De la definicion de descomposicion SVD vista en clase $U$ es una matriz ortogonal de tamaño $m\times m$, $Σ$ es una matriz diagonal $m\times n$ que contiene todos los valores singulares de la matriz original en su diagonal, y $V^{T}$ es la transpuesta de una matriz ortogonal $n\times n$

Considerando la Matriz identidad, al multiplicarla por cualquier matriz o Vector, esta no produce ninguna transformación, por lo que se puede decir que los valores propios de una matriz $I_n$ van a ser $\lambda_n=1$, debido a esto, la matriz $Σ=I_n$, con esto, la descomposicion SVD de la matriz identidad se puede simplificar como:

$$I_n=UV^{T}$$

Recordando el teorema $AA^{-1}=I$ (el orden no importa al ser matrices ortogonales), esto significa que las matrices $U, V^T$ deben ser inversas una de la otra, y al ser ortogonales se cumple que $A^{-1}=A^{T}$, por tanto

$$U^{-1}=V^{T}$$

esto significa entonces que $U=V$, esto permite simplificar mas la descomposicion SVD de la matriz identidad como:

$$I_n=UU^{T}$$

Ya que U es una matriz ortogonal, y del algebra lineal, hay infinitas matrices ortogonales ya que estas representan transformaciones como reflexiones y rotaciones en el espacio, y hay infinitas formas de rotar y reflectar. Por lo cual  hay infinitas formas de escribir $I_n=U\Sigma V^{T}$ siendo $U$ una matriz ortogonal.

Sabiendo que $V$ es una matriz ortogonal, se puede escribir la definicion de descomposicion SVD como

$$AV=UΣ$$

Escribiendo esto como componentes

$$Av_i=\sigma_i u_i \tag{1}$$

En otras palabras, la forma de escoger la matriz $V_r$ es verificando que se cumpla la condicion de la ecuacion (1), ya que, analizando esta ecuacion, la matriz $V_r$ correcta es aquella que al multiplicarla por la matriz original $A$, el resultado es una matriz cuyas columnas son las columnas $u_i$ de la matriz $U$, escaladas por el respectivo valor singular de la matriz $A$

Respecto a los autovectores con autovalores igual a 0, de la descomposicion SVD, si un valor singular es cero, al ser la raiz de los autovalores, el autovalor correspondiente de $A^{*}A$ (o $AA^{*}$) tambien es cero.

Sabiendo que los autovalores tambien representan la magnitud de una transformacion, los autovalores que correspoden a 0 nos dicen cuales "dimensiones", "direcciones" o "vectores" son "comprimidos" a 0, o nulificados por la matriz, ademas del algebra lineal, sabemos que si un autovalor es cero, esto significa que los infinitos autovectores asociados a este autovalor estan en el espacio nulo de $A^{*}A$ (o $AA^{*}$), y de las propiedades de los espacios vectoriales, el espacio nulo de $A^{*}A$ es igual al de $A$. Por lo que un autovalor igual a 0 nos dice que hay, al menos, un elemento en el espacio nulo de $A$, lo que lo hace mas grande, y por tanto distinto del espacio trivial de $A$, esto significa que la matriz no es invertible o singular.





